// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onyix.Services;

#nullable disable

namespace Onyix.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20230221030950_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Onyix.Entities.LevelSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLevelUpMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLevels")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelUpContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LevelUpTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL");

                    b.Property<int>("XpPerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpPerMessage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("LevelSettings");
                });

            modelBuilder.Entity("Onyix.Entities.UserKarma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Awards")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Downvotes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Posts")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Removed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Upvotes")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserKarma");
                });

            modelBuilder.Entity("Onyix.Entities.UserLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastGain")
                        .HasColumnType("TEXT");

                    b.Property<long>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalXP")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique();

                    b.ToTable("UserLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
