// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onyix.Services;

#nullable disable

namespace Onyix.Migrations
{
    [DbContext(typeof(DatabaseService))]
    partial class DatabaseServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Onyix.Database.LevelSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cooldown")
                        .HasColumnType("int");

                    b.Property<bool>("EnableLevelUpMessage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableLevels")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("LevelUpContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LevelUpTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double");

                    b.Property<int>("XpPerLevel")
                        .HasColumnType("int");

                    b.Property<int>("XpPerMessage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("LevelSettings");
                });

            modelBuilder.Entity("Onyix.Database.UserKarma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Awards")
                        .HasColumnType("bigint");

                    b.Property<long>("Downvotes")
                        .HasColumnType("bigint");

                    b.Property<long>("Posts")
                        .HasColumnType("bigint");

                    b.Property<long>("Removed")
                        .HasColumnType("bigint");

                    b.Property<long>("Upvotes")
                        .HasColumnType("bigint");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserKarma");
                });

            modelBuilder.Entity("Onyix.Database.UserLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("LastGain")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalXP")
                        .HasColumnType("bigint");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<long>("XP")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique();

                    b.ToTable("UserLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
